-- Table Schemas
DROP TABLE IF EXISTS body_temperature;
DROP TABLE IF EXISTS hourly_average_temperature;
DROP TABLE IF EXISTS daily_average_temperature;

CREATE TABLE body_temperature
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature DOUBLE NOT NULL,
    request_date DATE NOT NULL,
    request_time TIME NOT NULL
);

CREATE TABLE hourly_average_temperature
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature DOUBLE NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL
);

CREATE TABLE daily_average_temperature
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature DOUBLE NOT NULL,
    date DATE UNIQUE NOT NULL
);

INSERT INTO body_temperature(temperature, date, time)
VALUES (37.3, '2022-08-25', '15:12:20'),
       (37.2, '2022-08-25', '15:17:22'),
       (37.0, '2022-08-25', '15:22:21'),
       (37.1, '2022-08-25', '15:27:34'),
       (36.8, '2022-08-25', '15:32:33'),
       (36.9, '2022-08-25', '15:37:28'),
       (37.1, '2022-08-25', '15:42:30'),
       (37.1, '2022-08-25', '15:47:32'),
       (36.8, '2022-08-25', '15:52:33'),
       (36.9, '2022-08-25', '15:57:27'),
       (37.1, '2022-08-25', '16:02:34'),
       (37.0, '2022-08-25', '16:07:30'),
       (37.0, '2022-08-25', '16:12:30');


INSERT INTO hourly_average_temperature(temperature, date, time)
VALUES (37.2, '2022-08-25', '14:02:25'),
       (37.1, '2022-08-25', '15:02:34'),
       (36.8, '2022-08-25', '16:02:33'),
       (36.9, '2022-08-25', '17:02:27'),
       (37.1, '2022-08-25', '18:02:34'),
       (37.0, '2022-08-25', '19:02:30');

INSERT INTO daily_average_temperature(temperature, date)
VALUES (37.1, '2022-08-20'),
       (36.8, '2022-08-21'),
       (37.0, '2022-08-22'),
       (36.9, '2022-08-23'),
       (37.0, '2022-08-24'),
       (37.1, '2022-08-25');
